### ISSUE TITLE
Cleaner data communication between Python and C

### ISSUE THREAD

**Issue by mossblaser** [project-rig/network_tester#1]
At present, it is pretty messy to transfer structured experimental parameters and results between Python and C in this program. This issue is a place for me to outline my thoughts on the matter...

The experimental parameters are described in the form of a nested set of C structs and C primitive types arranged in arrays. Python's struct library only goes so-far in solving the translation problem by handling translation between C and Python primitives. It falls well short of anything more complex.

Proposed alternative API:

``` python
uint32_t = Primitive("I")
size_t = Primitive("I")
bool = Primitive("I")
double = Primitive("d")

# We define the datastructures to be used
traffic_node_source_t = Struct("traffic_node_source_t",
                               ("key", uint32_t),
                               ("num_received", uint32_t),
                               ("num_out_of_order", uint32_t),
                               ("last_seq_num", uint32_t))

traffic_node_type_t = Enum("traffic_node_type_t",
                           ("bernoulli", 0),
                           ("relay", 1))

traffic_node_spec_t = Struct("traffic_node_spec_t",
                             ("type", traffic_node_type_t),
                             ("key", uint32_t),
                             ("payload", bool),
                             ("num_sent", uint32_t),
                             ("num_sources", size_t),
                             ("sources", Pointer(Array(traffic_node_source_t))),
                             ("data",
                              # Note the anonymous structs/union types
                              Union(("bernoulli", Struct(("probability", double),
                                                         ("period", uint32_t))),
                                    ("relay", Struct()))))

network_node_spec_t = Struct("network_node_spec_t",
                             ("key_seq_mask", uint32_t),
                             ("duration", uint32_t),
                             ("num_traffic_nodes", size_t),
                             ("traffic_nodes", Pointer(Array(Pointer(traffic_node_spec_t)))))

for nn in nns:
    tn_specs = []
    for tn in tns:
        tn_spec = traffic_node_source_t(type=traffic_node_type_t.bernoulli,
                                        key=...,
                                        payload=...,
                                        num_sent=0,
                                        num_sources=0,
                                        data__bernouli__probability=...,
                                        data__bernouli__period=...)
        tn_source_specs = Array(traffic_node_source_t)()
        for source in tn.sources:
            source_spec = traffic_node_source_t(key=...,
                                                num_received=0,
                                                num_out_of_order=0,
                                                last_seq_num=0)
            tn_source_specs.append(source_spec)

        tn_spec.num_sources = len(tn_source_specs)
        tn_spec.sources = tn_source_specs
        tn_specs.append(tn_spec)

    tn_spec_pointers = Array(Pointer(traffic_node_source_t))()
    tn_spec_pointers.extend(tn_specs)

    nn_spec = network_node_spec_t(key_seq_mask=...,
                                  duration=...,
                                  num_traffic_nodes=len(tn_spec_pointers),
                                  traffic_nodes=tn_spec_pointers)

    # Assign all structures this object contains or points to a location in memory
    # in a continuous block with the specified object being the first in memory.
    # The relative_to value gives the memory address to assume nn_spec is relative
    # to and will be used when computing memory addresses in pointers.
    nn_spec.alloc(relative_to=0x00000000)

    sdram_write(nn_spec.pack())
```

**Comment by neworderofjamie** [comment]
I'd say that looks like a very nice, pythonic approach to this problem - I
would totally use it, but I'm still not 100% sure it's worth creating :)

**Comment by mossblaser** [comment]
> I would totally use it

If it ever gets built you'd be more than welcome :)

> but I'm still not 100% sure it's worth creating :)

You may well be right... Still, all this is very unpleasant(!)

**Comment by neworderofjamie** [comment]
One thought is (I'm not sure how heavyweight the c is), have you considered
something like google protobuffers? It does this and more
https://developers.google.com/protocol-buffers/docs/pythontutorial there is
a question as to how heavy weight the c implementations are. In C# it can
product a lightweight (in that case, non reflection reliant) serializer
that could application can use.

**Comment by mossblaser** [comment]
I've been looking at protobufs (along with lighter weight alternatives like this one: https://capnproto.org/) but the implementations are heavy. Additionally, you also need to hand-write the logic to "unpack" everything into your own data structures.

The thing about struct-like solutions is it costs you _zero_ SpiNNaker code space and C logic. It also means you only need to design two data structures: once for SpiNNaker and once for your Python which are likely to have inherently different data structures. The protobufs way generally means defining three since they don't _quite_ map onto Python's structures and certainly don't into simple C structures.

I was considering using JSON for which [very small parsers exist](http://zserge.com/jsmn.html) but this comes out very bulky to transfer. More compact JSON work-alikes exist but lack similarly good C parsers.

**Comment by mossblaser** [comment]
This issue was resolved by using sending configuration in the form of a sequence of "commands" to be executed which are trivially expressed and handled in both Python and C.
