### ISSUE TITLE
Add `sub_ms_packet_counters.py` to examples

### ISSUE THREAD

**Issue by mundya** [project-rig/network_tester#3]
Would you have any objection to adding `sub_ms_packet_counters.py` to the examples directory? It seems like something that might be of general use.

**Comment by neworderofjamie** [comment]
F.Y.I. for python 2.7 you need `raw_input()` not `input()`

**Comment by mundya** [comment]
Thankfully http://pythonhosted.org/six/#module-six.moves has `input` mapped appropriately

**Comment by mossblaser** [comment]
This would be a very good idea, though it probably needs a slight polish it would be a good example to have (as well as being a useful tool). In fact there are a handful of scripts I've handed out like this which have seen rather a lot of use. I'll attempt to do this when I'm back...

Things to add:
- [x] Sub-ms packet counter recording
- [x] Link throughput measurement
- [x] Link integrity tester

**Comment by mossblaser** [comment]
Sorted as of 27d54a1, thanks for the suggestion @mundya!

**Comment by mundya** [comment]
Actually 40c493b - thanks

**Comment by mossblaser** [comment]
...I was including the other two examples as well ;)
